### ISSUE TITLE
David-dm badge

### ISSUE THREAD

**Issue by j-brown** [conversant/ad-libs.js#5]
David-dm is a neat tool to manage deps in your project: https://david-dm.org/

One of the neat things about ad-libs is that it doesn't have any 3rd party dependencies. Adding a david-dm badge would display "dependencies: none" at the top of the readme. This might be a neat way to display how lightweight it is. Thoughts?

**Comment by jeffreytgilbert** [comment]
Solid suggestion. We do have dependencies for dev and testing though. We just don't have any external dependencies for the modules themselves.

**Comment by jeffreytgilbert** [comment]
We're going to file this under nice-to-have. If there's community support for the request, we can add it, but without actual dependencies it seems needless.

**Comment by jeffreytgilbert** [comment]
Manny snuck this in
